version: '2'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - "./schema:/docker-entrypoint-initdb.d/"
      - "./mysql-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
  spotify-manager:
    build: .
    command: nodemon server.js
    links:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - .:/user/src/app
    environment:
      SESSION_SECRET: ""
      MYSQL_HOST: "mysql"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "spotify_manager_db"
      AUTH0_DOMAIN: ""
      AUTH0_CLIENT_ID: ""
      AUTH0_CLIENT_SECRET: ""
      SPOTIFY_CLIENT_ID: ""
      SPOTIFY_CLIENT_SECRET: ""
volumes:
  mysql-data:
